language: python
python:
  - "2.7"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt

script:
  - python -m unittest

after_success:
  - coverage run --source htmldiffer setup.py test
  - coveralls
  - >
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "develop" ] ;
  then
  export DEPLOY_CONTENT='{"TRAVIS_BUILD_NUMBER":"'$TRAVIS_BUILD_NUMBER'","TRAVIS_COMMIT":"'$TRAVIS_COMMIT'","TRAVIS_BRANCH":"'$TRAVIS_BRANCH'","TRAVIS_REPO_SLUG":"'$TRAVIS_REPO_SLUG'"}' ;
  export DEPLOY_SIG="sha1=`echo -n "$DEPLOY_CONTENT" | openssl sha1 -hmac $DEPLOY_KEY | sed 's/^.* //'`" ;
  curl -X POST "$DEPLOY_URL" --data "$DEPLOY_CONTENT" -H "Content-Type: application/json" -H "X-Travis-Signature: $DEPLOY_SIG" ;
  fi